"""empty message

Revision ID: 4c748e295ed0
Revises: aed8d599b14b
Create Date: 2019-10-24 12:07:39.025000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c748e295ed0'
down_revision = 'aed8d599b14b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolios', sa.Column('skills', sa.String(length=200), nullable=True))
    op.add_column('portfolios', sa.Column('year', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolios', 'year')
    op.drop_column('portfolios', 'skills')
    # ### end Alembic commands ###
