"""empty message

Revision ID: aed8d599b14b
Revises: 
Create Date: 2019-10-24 12:06:07.236000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aed8d599b14b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolios', 'filter_alias')
    op.alter_column('role_user', 'role_id',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('role_user', 'user_id',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('roles', 'name',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=255),
               nullable=True)
    op.alter_column('sliders', 'desc',
               existing_type=mysql.TEXT(collation='utf8_unicode_ci'),
               nullable=True)
    op.alter_column('sliders', 'img',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=255),
               nullable=True)
    op.alter_column('sliders', 'title',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=255),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=255),
               nullable=True)
    op.alter_column('users', 'login',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=255),
               nullable=True)
    op.alter_column('users', 'name',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=255),
               nullable=True)
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=255),
               nullable=False)
    op.alter_column('users', 'name',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=255),
               nullable=False)
    op.alter_column('users', 'login',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=255),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=255),
               nullable=False)
    op.alter_column('sliders', 'title',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=255),
               nullable=False)
    op.alter_column('sliders', 'img',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=255),
               nullable=False)
    op.alter_column('sliders', 'desc',
               existing_type=mysql.TEXT(collation='utf8_unicode_ci'),
               nullable=False)
    op.alter_column('roles', 'name',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=255),
               nullable=False)
    op.alter_column('role_user', 'user_id',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('role_user', 'role_id',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.add_column('portfolios', sa.Column('filter_alias', mysql.VARCHAR(collation='utf8_unicode_ci', length=255), nullable=True))
    # ### end Alembic commands ###
